version: "2"
services:
  jirapokervue:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VUE_APP_HOST_BACKEND_URL: http://192.168.96.20:5001/
        VUE_APP_HOST_FRONTEND_PORT: 8081
    ports:
        - 8081:8081


